#!/bin/bash

# Generate ~/.msmtprc (mode 0600) from the resolved [mailer] section of
# config.toml.
#
# This replaces the old behaviour of symlinking a committed per-host
# msmtprc. There is one generic SMTP backend now: each user puts their own
# relay (host/port/from/user) in the [mailer] section of their
# config.toml, and the relay password lives only in their login Keychain —
# never committed. The [mailer] section is read via dasel (a guaranteed
# bootstrap primitive); it is no longer a sourceable shell snippet.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/config_common.sh"

echo "Setting up msmtp configuration..."

HOSTNAME_LOWER=$(get_hostname)
PROFILES=$(get_profiles "$REPO_ROOT" | paste -sd ' ' -)
echo "Detected hostname: $HOSTNAME_LOWER"
if [[ -n "$PROFILES" ]]; then
    echo "Using profiles (low to high priority): $PROFILES"
fi

# Read the [mailer] section of config.toml, resolved per-key single-winner
# across tiers (host > reverse(profiles) > default). Missing keys fall
# back to the defaults below.
MAILER="$(resolve_config_value "$REPO_ROOT" "mailer.backend")"
SMTP_HOST="$(resolve_config_value "$REPO_ROOT" "mailer.smtp_host")"
SMTP_PORT="$(resolve_config_value "$REPO_ROOT" "mailer.smtp_port")"
SMTP_FROM="$(resolve_config_value "$REPO_ROOT" "mailer.smtp_from")"
SMTP_USER="$(resolve_config_value "$REPO_ROOT" "mailer.smtp_user")"
SMTP_KEYCHAIN_SERVICE="$(resolve_config_value "$REPO_ROOT" "mailer.keychain_service")"
SMTP_TLS_TRUST_FILE="/etc/ssl/cert.pem"

# Apply defaults for the generic SMTP backend.
MAILER="${MAILER:-msmtp}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_KEYCHAIN_SERVICE="${SMTP_KEYCHAIN_SERVICE:-msmtp}"

if [[ "$MAILER" != "msmtp" ]]; then
    echo "[mailer] backend is '$MAILER', not 'msmtp' — skipping ~/.msmtprc generation"
    exit 0
fi

# Validate the required SMTP relay fields
MISSING=()
[[ -z "$SMTP_HOST" ]] && MISSING+=("SMTP_HOST")
[[ -z "$SMTP_FROM" ]] && MISSING+=("SMTP_FROM")
[[ -z "$SMTP_USER" ]] && MISSING+=("SMTP_USER")
if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo ""
    echo "WARNING: the [mailer] section of config.toml is missing required SMTP relay fields: ${MISSING[*]}"
    echo "Edit your config.toml (in the external host tier:"
    echo "  \${XDG_CONFIG_HOME:-~/.config}/macos-setup/config.toml)"
    echo "and set smtp_host, smtp_port, smtp_from, smtp_user under [mailer], then re-run 'make messaging'."
    echo "Skipping ~/.msmtprc generation."
    exit 0
fi

TARGET="$HOME/.msmtprc"

# Remove existing symlink or backup existing file
prepare_target "$TARGET"

echo "Generating $TARGET from the [mailer] section of config.toml..."

# Generate the msmtprc. The relay password is NOT stored here — msmtp reads
# it from the login Keychain at send time via passwordeval. The service name
# and username below MUST match the Keychain entry the user creates with
# `security add-generic-password` (see README and the config.toml template).
umask 077
cat > "$TARGET" <<EOF
# msmtp configuration — generated by scripts/msmtp_setup.sh from config.toml.
# Do not edit by hand: re-run 'make messaging' to regenerate.
# See: https://marlam.de/msmtp/msmtprc.txt

defaults
auth           on
tls            on
tls_trust_file $SMTP_TLS_TRUST_FILE
logfile        ~/.msmtp.log

account        default
host           $SMTP_HOST
port           $SMTP_PORT
from           $SMTP_FROM
user           $SMTP_USER
passwordeval   security find-generic-password -s $SMTP_KEYCHAIN_SERVICE -a $SMTP_USER -w
EOF

# msmtp requires restrictive permissions on its config file
chmod 600 "$TARGET"

# Warn (don't fail) if the Keychain entry is missing — the user may set it
# up after running 'make messaging'.
if ! security find-generic-password -s "$SMTP_KEYCHAIN_SERVICE" -a "$SMTP_USER" -w >/dev/null 2>&1; then
    echo ""
    echo "WARNING: no Keychain password found for service '$SMTP_KEYCHAIN_SERVICE'"
    echo "         account '$SMTP_USER'. msmtp will fail to authenticate until you add it:"
    echo ""
    echo "  security add-generic-password -s $SMTP_KEYCHAIN_SERVICE \\"
    echo "    -a $SMTP_USER -w 'YOUR_SMTP_PASSWORD'"
    echo ""
fi

echo "msmtp configuration setup complete!"
echo "Config file: $TARGET"
