#!/usr/bin/env bash

# Integration tests for `scripts/resolve_repo_root.sh` and
# `scripts/launchagent_runner.sh` (issue #133).
#
# Cases:
#   1. resolve_repo_root.sh prints the repo root for a valid
#      ~/.zsh-shared symlink (HOME redirected to a sandbox).
#   2. resolve_repo_root.sh fails loudly when ~/.zsh-shared is missing.
#   3. resolve_repo_root.sh fails loudly when ~/.zsh-shared is a
#      regular file (not a symlink).
#   4. resolve_repo_root.sh fails loudly when ~/.zsh-shared points
#      at a deleted target.
#   5. After moving the repo to a different path (and repointing
#      ~/.zsh-shared at the new location), resolve_repo_root.sh
#      returns the *new* path -- this is the "repo move" criterion
#      from the issue's acceptance list.
#   6. launchagent_runner.sh runs a command in --no-mail mode, cd's
#      into the repo root, and writes its log to
#      ~/Library/Logs/macos-setup/<job>.log (HOME sandboxed).
#   7. launchagent_runner.sh repeats case 6 against a *moved* repo
#      and still resolves the new path -- acceptance criterion 4.
#   8. launchagent_runner.sh rejects malformed argv (no '--', bad
#      <job> name) with non-zero exit and an explanatory message.
#   9. The Make-generated daily plist contains zero absolute paths
#      under the source repo (acceptance criterion 3). Generated by
#      stubbing the Makefile recipe just enough to write the plist
#      to a sandbox `LAUNCH_AGENTS_DIR` without actually invoking
#      `launchctl bootstrap`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SANDBOX_BASE="$REPO_ROOT/.claude/tmp/launchagent_runner_test"
FAIL=0

EXTRA_TMP_DIRS=()
cleanup_on_exit() {
    if [[ $FAIL -eq 0 ]]; then
        rm -rf "$SANDBOX_BASE"
        for d in "${EXTRA_TMP_DIRS[@]}"; do
            rm -rf "$d"
        done
    else
        echo
        echo "Sandbox preserved at: $SANDBOX_BASE" >&2
        for d in "${EXTRA_TMP_DIRS[@]}"; do
            echo "Extra tmp preserved at: $d" >&2
        done
    fi
}
trap cleanup_on_exit EXIT

mkdir -p "$SANDBOX_BASE"

# ---- helpers ----
fail() {
    echo "FAIL: $*" >&2
    FAIL=1
}

pass() {
    echo "PASS: $*"
}

# Create an isolated $HOME with a `.zsh-shared` symlink that points
# at $1/shared/zsh.
mk_fake_home() {
    local repo_dir="$1"
    local home_dir="$2"
    rm -rf "$home_dir"
    mkdir -p "$home_dir"
    ln -s "$repo_dir/shared/zsh" "$home_dir/.zsh-shared"
}

# Build a minimal fake repo containing just shared/zsh/ and scripts/.
# Mirrors the real-repo `shared/zsh/launchagent_runner` relative
# symlink so cases that exec the runner through that path can do so.
mk_fake_repo() {
    local dst="$1"
    rm -rf "$dst"
    mkdir -p "$dst/shared/zsh"
    cp "$REPO_ROOT/shared/zsh/macos_setup.zsh" "$dst/shared/zsh/"
    mkdir -p "$dst/scripts"
    cp "$REPO_ROOT/scripts/resolve_repo_root.sh" "$dst/scripts/"
    cp "$REPO_ROOT/scripts/launchagent_runner.sh" "$dst/scripts/"
    chmod +x "$dst/scripts/"*.sh
    ln -s ../../scripts/launchagent_runner.sh "$dst/shared/zsh/launchagent_runner"
}

# ---- Case 1: happy-path resolver ----
case1_repo="$SANDBOX_BASE/case1/repo"
case1_home="$SANDBOX_BASE/case1/home"
mk_fake_repo "$case1_repo"
mk_fake_home "$case1_repo" "$case1_home"

actual="$(HOME="$case1_home" "$case1_repo/scripts/resolve_repo_root.sh")"
if [[ "$actual" == "$case1_repo" ]]; then
    pass "case 1: resolver returns the expected repo root ($actual)"
else
    fail "case 1: expected '$case1_repo', got '$actual'"
fi

# ---- Case 2: missing symlink ----
case2_home="$SANDBOX_BASE/case2/home"
rm -rf "$case2_home"
mkdir -p "$case2_home"
if HOME="$case2_home" "$case1_repo/scripts/resolve_repo_root.sh" >/dev/null 2>&1; then
    fail "case 2: resolver should have failed for missing symlink"
else
    pass "case 2: resolver fails for missing ~/.zsh-shared"
fi

# ---- Case 3: regular file at ~/.zsh-shared ----
case3_home="$SANDBOX_BASE/case3/home"
rm -rf "$case3_home"
mkdir -p "$case3_home"
echo "not a symlink" > "$case3_home/.zsh-shared"
if HOME="$case3_home" "$case1_repo/scripts/resolve_repo_root.sh" >/dev/null 2>&1; then
    fail "case 3: resolver should have failed for regular-file symlink slot"
else
    pass "case 3: resolver fails for regular file at ~/.zsh-shared"
fi

# ---- Case 4: dangling symlink ----
case4_home="$SANDBOX_BASE/case4/home"
rm -rf "$case4_home"
mkdir -p "$case4_home"
ln -s "$SANDBOX_BASE/case4/does-not-exist" "$case4_home/.zsh-shared"
if HOME="$case4_home" "$case1_repo/scripts/resolve_repo_root.sh" >/dev/null 2>&1; then
    fail "case 4: resolver should have failed for dangling symlink"
else
    pass "case 4: resolver fails for dangling ~/.zsh-shared"
fi

# ---- Case 5: repo move ----
case5_old="$SANDBOX_BASE/case5/old-location/repo"
case5_new="$SANDBOX_BASE/case5/NEW/path/macos-setup"
case5_home="$SANDBOX_BASE/case5/home"
mk_fake_repo "$case5_old"
mk_fake_home "$case5_old" "$case5_home"

# Move repo, repoint the symlink (this simulates `make shell` rerun)
mkdir -p "$(dirname "$case5_new")"
mv "$case5_old" "$case5_new"
rm "$case5_home/.zsh-shared"
ln -s "$case5_new/shared/zsh" "$case5_home/.zsh-shared"

actual="$(HOME="$case5_home" "$case5_new/scripts/resolve_repo_root.sh")"
if [[ "$actual" == "$case5_new" ]]; then
    pass "case 5: resolver follows repo move ($actual)"
else
    fail "case 5: expected '$case5_new', got '$actual'"
fi

# ---- Case 6: launchagent_runner.sh runs in --no-mail mode ----
case6_repo="$SANDBOX_BASE/case6/repo"
case6_home="$SANDBOX_BASE/case6/home"
mk_fake_repo "$case6_repo"
mk_fake_home "$case6_repo" "$case6_home"

HOME="$case6_home" "$case6_repo/scripts/launchagent_runner.sh" \
    test-job -- /bin/sh -c 'echo "cwd is: $(pwd)"; echo "marker-output"'

log_file="$case6_home/Library/Logs/macos-setup/test-job.log"
if [[ ! -f "$log_file" ]]; then
    fail "case 6: log file not created at $log_file"
elif ! grep -q "marker-output" "$log_file"; then
    fail "case 6: log file missing expected command output"
elif ! grep -q "REPO_ROOT=$case6_repo" "$log_file"; then
    fail "case 6: log file missing REPO_ROOT line for '$case6_repo'"
elif ! grep -q "cwd is: $case6_repo" "$log_file"; then
    fail "case 6: command did not run with cwd=repo root"
else
    pass "case 6: launchagent_runner runs and logs to ~/Library/Logs/macos-setup/"
fi

# ---- Case 7: launchagent_runner after repo move ----
case7_old="$SANDBOX_BASE/case7/old/repo"
case7_new="$SANDBOX_BASE/case7/NEW/repo"
case7_home="$SANDBOX_BASE/case7/home"
mk_fake_repo "$case7_old"
mk_fake_home "$case7_old" "$case7_home"

mkdir -p "$(dirname "$case7_new")"
mv "$case7_old" "$case7_new"
rm "$case7_home/.zsh-shared"
ln -s "$case7_new/shared/zsh" "$case7_home/.zsh-shared"

# Invoke the runner via the symlink path so we exactly mimic what
# launchd does at fire time: it execs
# `$HOME/.zsh-shared/launchagent_runner`, which is a symlink whose
# target is `../../scripts/launchagent_runner.sh` resolved against
# the symlink target dir (= <repo>/shared/zsh), i.e. <repo>/scripts/
# launchagent_runner.sh. With the repo moved, the now-repointed
# ~/.zsh-shared symlink takes us to the new location automatically.
HOME="$case7_home" "$case7_home/.zsh-shared/launchagent_runner" \
    moved-job -- /bin/sh -c 'echo "ran in: $(pwd)"'

log_file="$case7_home/Library/Logs/macos-setup/moved-job.log"
if [[ ! -f "$log_file" ]]; then
    fail "case 7: log file not created at $log_file"
elif ! grep -q "ran in: $case7_new" "$log_file"; then
    fail "case 7: expected cwd=$case7_new in log; got:" && cat "$log_file" >&2
else
    pass "case 7: launchagent_runner picks up moved repo via ~/.zsh-shared"
fi

# ---- Case 8: bad argv ----
case8_repo="$SANDBOX_BASE/case8/repo"
case8_home="$SANDBOX_BASE/case8/home"
mk_fake_repo "$case8_repo"
mk_fake_home "$case8_repo" "$case8_home"

# No '--'
if HOME="$case8_home" "$case8_repo/scripts/launchagent_runner.sh" \
        somejob /bin/echo hi >/dev/null 2>&1; then
    fail "case 8a: runner should reject missing '--'"
else
    pass "case 8a: runner rejects missing '--'"
fi

# Bad job name (path traversal)
if HOME="$case8_home" "$case8_repo/scripts/launchagent_runner.sh" \
        ../bad -- /bin/echo hi >/dev/null 2>&1; then
    fail "case 8b: runner should reject bad job name"
else
    pass "case 8b: runner rejects bad job name"
fi

# Too few args
if HOME="$case8_home" "$case8_repo/scripts/launchagent_runner.sh" \
        toofew >/dev/null 2>&1; then
    fail "case 8c: runner should reject missing argv"
else
    pass "case 8c: runner rejects missing argv"
fi

# ---- Case 9: Make-generated plist has no repo absolute paths ----
# We can't run `launchctl bootstrap` in a sandbox, but we can drive
# the Makefile to write the plist into a sandboxed LAUNCH_AGENTS_DIR.
# Stub `launchctl` and `scripts/resolve_mailto.sh` via PATH.
case9_dir="$SANDBOX_BASE/case9"
case9_stub_bin="$case9_dir/stubs"
case9_launchagents="$case9_dir/LaunchAgents"
case9_logs="$case9_dir/Logs/macos-setup"
mkdir -p "$case9_stub_bin" "$case9_launchagents" "$case9_logs"

cat > "$case9_stub_bin/launchctl" <<'EOF'
#!/bin/sh
exit 0
EOF
chmod +x "$case9_stub_bin/launchctl"

# Override resolve_mailto.sh by making it return empty
RESOLVE_STUB="$case9_dir/resolve_mailto.sh"
cat > "$RESOLVE_STUB" <<'EOF'
#!/bin/sh
exit 0
EOF
chmod +x "$RESOLVE_STUB"

# Run `make schedule-daily` against the real Makefile with the
# sandboxed dirs overridden. We avoid actually mucking with the
# user's installed agents by giving it our own LAUNCH_AGENTS_DIR.
# The Makefile invokes `scripts/resolve_mailto.sh` relative to CWD,
# so we need to run it from a directory where that script exists.
# Easiest: shadow the script via PATH-relative invocation by setting
# up a fake "scripts" tree pointing at our stub.
case9_work="$case9_dir/work"
mkdir -p "$case9_work/scripts"
cp "$RESOLVE_STUB" "$case9_work/scripts/resolve_mailto.sh"
chmod +x "$case9_work/scripts/resolve_mailto.sh"
cp "$REPO_ROOT/Makefile" "$case9_work/Makefile"
# Also ensure other referenced sub-Makefiles or scripts the
# schedule-daily recipe touches are present. Right now the recipe
# only calls `scripts/resolve_mailto.sh` and `launchctl`, so the
# stubs above are sufficient.

# Use a $HOME that is *not* under the repo, so any absolute-repo
# path that leaks into the plist is unambiguously offending. We
# need this OUTSIDE the repo since the test's normal sandbox lives
# under `.claude/tmp/`, and the test asserts the plist contains
# no path containing the repo root. `mktemp -d` in /tmp is safe.
case9_home_outside="$(mktemp -d /tmp/macos-setup-launchagent-test.XXXXXX)"
EXTRA_TMP_DIRS+=("$case9_home_outside")

PATH="$case9_stub_bin:$PATH" \
    HOME="$case9_home_outside" \
    make -C "$case9_work" -s schedule-daily \
        LAUNCH_AGENTS_DIR="$case9_launchagents" \
        LAUNCHAGENT_LOG_DIR="$case9_logs" \
        >"$case9_dir/make.out" 2>&1 || {
            echo "--- make output ---"
            cat "$case9_dir/make.out" >&2
            fail "case 9: 'make schedule-daily' returned non-zero in sandbox"
        }

plist="$case9_launchagents/com.macos-setup.daily-update.plist"
if [[ ! -f "$plist" ]]; then
    fail "case 9: plist not generated at $plist"
else
    # Acceptance criterion 3: no absolute paths under the source
    # repo should appear in the generated plist.
    real_repo="$(cd "$REPO_ROOT" && pwd -P)"
    if grep -F "$real_repo" "$plist" >/dev/null 2>&1; then
        echo "--- offending plist content ---" >&2
        cat "$plist" >&2
        fail "case 9: plist embeds absolute path under repo ($real_repo)"
    else
        pass "case 9: generated plist contains no absolute repo paths"
    fi
    # Sanity: the runner path should reference ~/.zsh-shared/launchagent_runner
    # (the new symlink-chain approach), not the old ../scripts/ shape.
    if grep -F "$case9_home_outside/.zsh-shared/launchagent_runner" "$plist" >/dev/null 2>&1; then
        pass "case 9: plist ProgramArguments[0] points at ~/.zsh-shared/launchagent_runner"
    else
        echo "--- plist content ---" >&2
        cat "$plist" >&2
        fail "case 9: plist ProgramArguments[0] is not the expected symlink-chain runner path"
    fi
fi

# ---- Case 10: launchagent_runner exports HOMEBREW_NO_ASK (issue #20) ----
# launchd never sources ~/.zshrc, so the runner itself must export
# HOMEBREW_NO_ASK=1; otherwise a scheduled `make update` hangs forever
# on Homebrew 6.0's interactive `[y/n]` ask-mode prompt. Assert the
# child command sees the variable set to 1 in its environment.
case10_repo="$SANDBOX_BASE/case10/repo"
case10_home="$SANDBOX_BASE/case10/home"
mk_fake_repo "$case10_repo"
mk_fake_home "$case10_repo" "$case10_home"

# Run with HOMEBREW_NO_ASK unset in the parent env so the only way the
# child can see it is if the runner exported it. `env -u` scrubs any
# value inherited from the test's own shell.
HOME="$case10_home" env -u HOMEBREW_NO_ASK \
    "$case10_repo/scripts/launchagent_runner.sh" \
    ask-job -- /bin/sh -c 'echo "NO_ASK=[${HOMEBREW_NO_ASK:-UNSET}]"'

log_file="$case10_home/Library/Logs/macos-setup/ask-job.log"
if [[ ! -f "$log_file" ]]; then
    fail "case 10: log file not created at $log_file"
elif ! grep -q "NO_ASK=\[1\]" "$log_file"; then
    echo "--- log content ---" >&2
    cat "$log_file" >&2
    fail "case 10: child command did not see HOMEBREW_NO_ASK=1"
else
    pass "case 10: launchagent_runner exports HOMEBREW_NO_ASK=1 to the job"
fi

# ---- summary ----
echo
if [[ $FAIL -eq 0 ]]; then
    echo "All tests passed."
else
    echo "One or more tests failed." >&2
    exit 1
fi
